apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: etcd-service  # 配置无头服务，见后面的Service配置
  replicas: 3                # etcd 集群的副本数量
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.0
        command:
          - /usr/local/bin/etcd
          - --data-dir=/etcd-data
          - --name=$(POD_NAME)
          - --initial-advertise-peer-urls=http://$(POD_NAME).etcd-service.default.svc.cluster.local:2380
          - --listen-peer-urls=http://0.0.0.0:2380
          - --listen-client-urls=http://0.0.0.0:2379
          - --advertise-client-urls=http://$(POD_NAME).etcd-service.default.svc.cluster.local:2379
          - --initial-cluster=etcd-0=http://etcd-0.etcd-service.default.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-service.default.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-service.default.svc.cluster.local:2380
          - --initial-cluster-state=new
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 2379
        - containerPort: 2380
        livenessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 10         # 根据etcd启动时间调整
          periodSeconds: 10               # 每10秒检查一次
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
      volumes:
      - name: etcd-data
        emptyDir: {}