apiVersion: v1
kind: Service
metadata:
  name: personal-project-service-service
spec:
  type: NodePort
  selector:
    app: personal-project-service-pod  # 确保与 Pod 的标签匹配
  ports:
  - protocol: TCP
    port: 8891 # Service暴露的端口
    targetPort: 8891 # 转发到容器的端口
  
