
apiVersion: v1
kind: ConfigMap
metadata:
  name: personal-notify-service-config
data:
  production.yml: |
    server:
      listen-address: 0.0.0.0:8892
      service-name: personal-notify-service

    etcd:
      endpoint:
        - http://etcd-0.etcd-service.default.svc.cluster.local:2379
        - http://etcd-1.etcd-service.default.svc.cluster.local:2379
        - http://etcd-2.etcd-service.default.svc.cluster.local:2379

    open-telemetry:
      endpoint: jaeger.default.svc.cluster.local:4317

    keys:
      sct-key: xxxx

