apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app  # 确保与 Pod 的标签匹配
  ports:
  - protocol: TCP
    port: 8001    # Service暴露的端口
    targetPort: 8000 # 转发到容器的8888端口
  type: LoadBalancer # 使用 LoadBalancer 类型将端口暴露到外部
