apiVersion: v1
kind: Pod
metadata:
  name: go-app
spec:
  replicas: 2  # 设置副本数量
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-container
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "--"]
        args:
          - |
            apt-get update && \
            apt-get install -y golang git && \
            git clone https://github.com/li1553770945/sheepim-api-gateway /app && \
            chmod +x /app/build.sh && \
            /app/build.sh && \
            /app/output/boostrap.sh 
        ports:
        - containerPort: 8000