apiVersion: v1
kind: Service
metadata:
  name: sheepim-api-gateway-service
spec:
  type: NodePort
  selector:
    app: sheepim-api-gateway-pod  # 确保与 Pod 的标签匹配
  ports:
  - protocol: TCP
    port: 9100    # Service暴露的端口
    targetPort: 9100 # 转发到容器的端口
    nodePort: 31900
  
