apiVersion: v1
kind: ConfigMap
metadata:
  name: sheepim-api-gateway-config
data:
  production.yml: |
    server:
      listen-address: 0.0.0.0:9100
      service-name: sheepim-api-gateway
    etcd:
      endpoint:
        - http://etcd-0.etcd-service.default.svc.cluster.local:2379
        - http://etcd-1.etcd-service.default.svc.cluster.local:2379
        - http://etcd-2.etcd-service.default.svc.cluster.local:2379

    open-telemetry:
      endpoint: jaeger.default.svc.cluster.local:4317

    rpc:
      user-service-name: sheepim-user-service
      auth-service-name: sheepim-auth-service
      project-service-name: personal-project-service
      feedback-service-name: personal-feedback-service