apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheepim-api-gateway-deployment
spec:
  replicas: 3  # 设置副本数量
  selector:
    matchLabels:
      app: sheepim-api-gateway-pod
  template:
    metadata:
      labels:
        app: sheepim-api-gateway-pod
    spec:
      containers:
      - name: sheepim-api-gateway-container
        image: peacesheep/sheepim-api-gateway:latest
        volumeMounts:
        - name: config-volume
          mountPath: /app/conf  
          readOnly: true
        ports:
        - containerPort: 9100
        livenessProbe:                      # 存活探针，检测是否正常运行
          httpGet:
            path: /api/ping                        # 检查根路径
            port: 9100                   
          initialDelaySeconds: 10          
          periodSeconds: 10                # 每10秒检查一次
          timeoutSeconds: 5                # 探针的超时时间
          failureThreshold: 3              # 连续失败3次则重启
        readinessProbe:                     # 就绪探针，检测服务是否可用
          httpGet:
            path: /api/ping                        # 检查根路径
            port: 9100                  
          initialDelaySeconds: 5           # 延迟5秒开始检测
          periodSeconds: 5                 # 每5秒检测一次
          timeoutSeconds: 5                # 探针的超时时间
          failureThreshold: 3              # 连续失败3次则视为不可用
      volumes:
      - name: config-volume
        configMap:
          name: sheepim-api-gateway-config
