
apiVersion: v1
kind: ConfigMap
metadata:
  name: sheepim-push-proxy-service-config
data:
  production.yml: |
    server:
        listen-address: 0.0.0.0:8896
        service-name: sheepim-push-proxy-service
    etcd:
      endpoint:
        - http://etcd-0.etcd-service.default.svc.cluster.local:2379
        - http://etcd-1.etcd-service.default.svc.cluster.local:2379
        - http://etcd-2.etcd-service.default.svc.cluster.local:2379

    open-telemetry:
      endpoint: otelcol-service.default.svc.cluster.local:4317

    kafka:
      brokers:
        - "kafka-service.default.svc.cluster.local:9092"
      topic: messages
      group-id: group1
      
