
apiVersion: v1
kind: ConfigMap
metadata:
  name: sheepim-room-service-config
data:
  production.yml: |
    server:
      listen-address: 0.0.0.0:8893
      service-name: sheepim-room-service

    etcd:
      endpoint:
        - http://etcd-0.etcd-service.default.svc.cluster.local:2379
        - http://etcd-1.etcd-service.default.svc.cluster.local:2379
        - http://etcd-2.etcd-service.default.svc.cluster.local:2379

    open-telemetry:
      endpoint: jaeger.default.svc.cluster.local:4317

    rpc:
      auth-service-name: sheepim-auth-service
    
    cache:
      endpoint: redis-service.default.svc.cluster.local:6379
      database: 0
      password: 
      expire-seconds: 86400
      

