apiVersion: v1
kind: Service
metadata:
  name: sheepim-room-service-service
spec:
  type: ClusterIP
  selector:
    app: sheepim-room-service-pod  # 确保与 Pod 的标签匹配
  ports:
  - protocol: TCP
    port: 8893    # Service暴露的端口
    targetPort: 8893 # 转发到容器的端口
  
