apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: LoadBalancer
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
    - name: otlp-http
      port: 4371
      targetPort: 4371
  selector:
    app: jaeger

