apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
      nodePort: 31686
    - name: otlp-http
      port: 4317
      targetPort: 4317
  selector:
    app: jaeger

