apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus-pod
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 31690
  
