name: 🐛 Bug Report
description: 提交程序错误报告
title: "[Bug] 简明问题描述"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **请按格式填写以下内容**
  - type: input
    id: environment
    attributes:
      label: 环境信息
      description: "操作系统/浏览器/项目版本/dev模式 or vscode插件"
      placeholder: "例如: Windows 11 / Chrome 120 / v2.1.0 / dev模式"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 如何触发的错误？（按数字列表格式）"
      placeholder: |
        1. 
        2. 
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
    validations:
      required: true
  - type: textarea
    id: expectedee
    attributes:
      label: 预期行为
    validations:
      required: true