apiVersion: v1
kind: PersistentVolume
metadata:
  name: infisical-postgresql-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  claimRef:
    namespace: infisical
    name: data-postgresql-0
  hostPath:
    path: /mnt/data/infisical/postgresql
    type: DirectoryOrCreate
