apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
data:
  otelcol-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    exporters:
      otlphttp: 
        endpoint: "http://jaeger.default.svc.cluster.local:4318"
      prometheus: 
        endpoint: "0.0.0.0:9464"

    processors:
      batch: # 批量处理提高性能
        timeout: 1s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]


