server {
    listen       80;
    server_name  api.peacesheep.xyz;

    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    server_name  api.peacesheep.xyz localhost;

    ssl_certificate     /etc/letsencrypt/live/peacesheep.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/peacesheep.xyz/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location /api {
        gzip off;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding on;
        proxy_connect_timeout 300s;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        if ($http_origin ~* (https://peacesheep\.xyz|https://www\.peacesheep\.xyz)) {
            add_header 'Access-Control-Allow-Origin' "$http_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
        }

        proxy_pass http://localhost:31900/api;
    }
}
