server {
    listen       80;
    server_name  socket.peacesheep.xyz;

    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    server_name  socket.peacesheep.xyz;

    ssl_certificate     /etc/letsencrypt/live/peacesheep.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/peacesheep.xyz/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location /connect {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        if ($http_origin ~* (https://store.peacesheep\.xyz)) {
            add_header 'Access-Control-Allow-Origin' "$http_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
        }

        proxy_pass http://localhost:31901;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;

        proxy_read_timeout 36000s;
        proxy_send_timeout 36000s;
        proxy_connect_timeout 60s;
        keepalive_timeout 36000s;
    }
}
