
apiVersion: v1
kind: ConfigMap
metadata:
  name: sheepim-connect-service-config
data:
  production.yml: |
    server:
      ws-listen-address: 0.0.0.0:9101
      rpc-listen-address: 0.0.0.0:8894
      service-name: sheepim-connect-service

    etcd:
      endpoint:
        - http://etcd-0.etcd-service.default.svc.cluster.local:2379
        - http://etcd-1.etcd-service.default.svc.cluster.local:2379
        - http://etcd-2.etcd-service.default.svc.cluster.local:2379

    open-telemetry:
      endpoint: otelcol-service.default.svc.cluster.local:4317

    rpc:
      auth-service-name: sheepim-auth-service
      online-service-name: sheepim-online-service
      push-proxy-service-name: sheepim-push-proxy-service
      room-service-name: sheepim-room-service
      
