apiVersion: v1
kind: Service
metadata:
  name: sheepim-connect-service-service
spec:
  type: NodePort
  selector:
    app: sheepim-connect-service-pod  # 确保与 Pod 的标签匹配
  ports:
  - protocol: TCP
    port: 8894   # Service暴露的端口
    targetPort: 8894 # 转发到容器的端口
    name: rpc
  - protocol: TCP
    port: 9101    # Service暴露的端口
    targetPort: 9101 # 转发到容器的端口
    nodePort: 31901
    name: http