
apiVersion: v1
kind: ConfigMap
metadata:
  name: personal-file-service-config
data:
  production.yml: |
    server:
      listen-address: 0.0.0.0:8898
      service-name: personal-file-service

    etcd:
      endpoint:
        - http://etcd-0.etcd-service.default.svc.cluster.local:2379
        - http://etcd-1.etcd-service.default.svc.cluster.local:2379
        - http://etcd-2.etcd-service.default.svc.cluster.local:2379

    open-telemetry:
      endpoint: otelcol-service.default.svc.cluster.local:4317

    database:
      username: xxx
      password: xx
      database: xxx
      address: xxx
      port: xxx
    cos:
      ak: xxx
      sk: xxx
      endpoint: https://xxx.cos.accelerate.myqcloud.com
