apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pod
  serviceName: "kafka"
  template:
    metadata:
      labels:
        app: kafka-pod
    spec:
      containers:
      - name: kafka-container
        image: bitnami/kafka:4.0.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper-service.default.svc.cluster.local:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
          value: "1"
        - name: KAFKA_CFG_BROKER_ID
          value: "0"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service.default.svc.cluster.local:9092
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS
          value: "1"
        - name: KAFKA_CFG_AUTO_COMMIT_INTERVAL_MS
          value: "500" # 每秒自动提交偏移量
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker"
        - name: KAFKA_CFG_NODE_ID
          value: "0"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
