apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-pod
  serviceName: "zookeeper-service"
  template:
    metadata:
      labels:
        app: zookeeper-pod
    spec:
      containers:
      - name: zookeeper-container
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_SERVERS
          value: "server.1=0.0.0.0:2888:3888"
        - name: ZOO_STANDALONE_ENABLED
          value: "true"  # 启用单节点模式