apiVersion: v1
kind: Service
metadata:
  name: sheepim-push-worker-service-service
spec:
  type: ClusterIP
  selector:
    app: sheepim-push-worker-service-pod  # 确保与 Pod 的标签匹配
  ports:
  - protocol: TCP
    port: 8897   # Service暴露的端口
    targetPort: 8897 # 转发到容器的端口
    name: rpc
