
apiVersion: v1
kind: ConfigMap
metadata:
  name: sheepim-user-service-config
data:
  production.yml: |
    server:
      listen-address: 0.0.0.0:8889
      service-name: sheepim-auth-service

    etcd:
      endpoint:
        - http://etcd-0.etcd-service.default.svc.cluster.local:2379
        - http://etcd-1.etcd-service.default.svc.cluster.local:2379
        - http://etcd-2.etcd-service.default.svc.cluster.local:2379

    open-telemetry:
      endpoint: jaeger.default.svc.cluster.local:4317

    database:
      username: xxx
      password: xx
      database: xxx
      address: xxx
      port: xxx

    rpc:
      user-service-name: sheepim-user-service

